#' plot_labelingefficiency
#' @param evidence Data.frame,
#' evidence table originating from MaxQuant.
#' @return A scatter plot (generated by \code{\link[ggplot2]{ggplot}})
#' @examples
#' #' if(interactive()){
#' data("evidence.raw")
#' evidencedata <- evidence.raw
#' plot_labelingefficiency(evidencedata)
#' }
#' @import dplyr
#' @import ggplot2
#' @export
plot_labelingefficiency <-  function (evidence) {
  evidence %>% as_tibble() %>%
    group_by(Type) %>%
    summarise(n = n()) %>%
    mutate(freq = n / sum(n)) %>%
    mutate(g="Type") %>%
    ggplot(aes(x = factor(g), y = freq*100, fill = factor(Type))) +
    geom_bar(stat="identity", width = 0.7) +
    labs(x = "", y = "Percentage (%)", fill = "Type") +
    theme_minimal(base_size = 14)

}
